# -*- coding: utf-8 -*-
"""DigitoUnico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/reneandrad/DigitoUnico/blob/main/DigitoUnico.ipynb
"""

def digitoUnico (n,k):
    if (n>=1 and n<= 10 **1000000) and (k>=1 and k<= 10 **5):
        nk =str(n) * k
        soma = int(sum(int(i) for i in str(nk)))
    
        if len(str(soma))==1:
            return soma
    
        else:
            return digitoUnico (soma,1)
    
    else:
        print("Número fora dos paramentros")

n = int(input("Digite o número que deseja calcular o Dígito Único: "))

k = int(input("Informe a quantidade de repetições do número: "))

print("O Dígito Único de", n, "em",k,"repetições é:", digitoUnico(n,k))